services:
  admin-console:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/donasbydonation/admin-console:local
    ports:
      - "30800:8000"
    networks:
      - develop-environment
    environment:
      - "APP_API_HOST=server"
      - "APP_API_PORT=8080"
      - "APP_ADM_CONTAINER_PORT=8000"

networks:
  develop-environment:
    name: develop-environment
    external: true
